name: Load env variables

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run Unit Tests
      runs-on: windows-11

    steps:
      - name: Load env variables
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
